Profil utilisateur
Quentin1814/S5.01 pull request #22
Opened 2024-02-15 08:41 UTC by NoeJouve

2024-02-15 08:49 UTC, Quentin1814 requested changes
Trop de choses à changer, pas approuvé

2024-02-15 08:49 UTC, Quentin1814 commented on app/src/main/AndroidManifest.xml
> -    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
à remettre

2024-02-15 08:50 UTC, MikeIUTBayonne reviewed
Revenir à l'identifiant de base pour le TextView dans le fichier activity_map.xml ligne 195.

2024-02-16 13:20 UTC, MikeIUTBayonne commented
Changement intégré via une autre pull request

2024-02-16 13:20 UTC, closed without merging